# Generated by Django 5.0 on 2023-12-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('longitud', models.FloatField()),
            ],
        ),
    ]
