# Generated by Django 5.0 on 2024-01-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_articulo_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de la categoria')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion de la categoria')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del artículo')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación del artículo')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='categorias',
            field=models.ManyToManyField(to='principal.categoria', verbose_name='Categorias'),
        ),
    ]
