# Generated by Django 5.0.1 on 2024-01-23 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de la competicion')),
                ('lugar', models.CharField(max_length=50, verbose_name='Lugar de la competicion')),
                ('fecha', models.DateField(verbose_name='Fecha de la competicion')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del artículo')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación del artículo')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del equipo')),
                ('categoria', models.CharField(max_length=30, verbose_name='Categoria del equipo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del artículo')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación del artículo')),
                ('competicion', models.ManyToManyField(to='principal.competicion')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable del equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del jugador')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo del jugador')),
                ('edad', models.IntegerField(verbose_name='Edad del jugador')),
                ('foto', models.ImageField(upload_to='', verbose_name='Foto del jugador')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del artículo')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación del artículo')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.equipo')),
            ],
        ),
    ]
