# Generated by Django 5.0.1 on 2024-01-16 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del artículo')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación del artículo')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del artículo')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación del artículo')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del artículo')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación del artículo')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.equipo')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
