# Generated by Django 5.0.1 on 2024-01-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competicion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={},
        ),
        migrations.AddField(
            model_name='competicion',
            name='fecha',
            field=models.DateField(default='01/01/2000', verbose_name='Fecha de la competicion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competicion',
            name='lugar',
            field=models.CharField(default='01/01/2000', max_length=50, verbose_name='Lugar de la competicion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competicion',
            name='nombre',
            field=models.CharField(default='', max_length=30, verbose_name='Nombre de la competicion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(default='', max_length=30, verbose_name='Categoria del equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='competicion',
            field=models.ManyToManyField(to='principal.competicion'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(default='', max_length=30, verbose_name='Nombre del equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='correo',
            field=models.EmailField(default='', max_length=254, verbose_name='Correo del jugador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='edad',
            field=models.IntegerField(default='', verbose_name='Edad del jugador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='foto',
            field=models.ImageField(default='', upload_to='', verbose_name='Foto del jugador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(default='', max_length=30, verbose_name='Nombre del jugador'),
            preserve_default=False,
        ),
    ]
